colors:
  # Default colors
  primary:
    background: '#111111'
    foreground: '#FFFFFF'
 
 # Normal colors
  normal:
    black:   '#111111'
    red:     '#cc6666'
    green:   '#b5bd68'
    yellow:  '#f0c674'
    blue:    '#828482'
    magenta: '#b294bb'
    cyan:    '#8abeb7'
    white:   '#c5c8c6'

 # Bright colors
  bright:
    black:   '#828482'
    red:     '#d54e53'
    green:   '#b9ca4a'
    yellow:  '#e7c547'
    blue:    '#828482'
    magenta: '#c397d8'
    cyan:    '#70c0b1'
    white:   '#FFFFFF'